language: node_js

node_js:
  - "node"

cache:
  - yarn

script:
  - yarn lint
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep_history: true
  local_dir: dist # Folder to deploy on the gh-page
  fqdn: shuvasisdatta.com # Custom domain
  on:
    branch: master
