language: node_js

node_js:
  - "node"

cache:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist # folder to deploy on the gh-page
  on:
    branch: master
